### ISSUE TITLE
오답노트 오류

### ISSUE THREAD

**Issue by zmania** [Mangongso/MamaOMR#144]
테스트 참가 완료 후 오답노드 작성하면 문제가 두번 등록 됨
mamaomr.hanbnc.com/smart_omr/exercise_book/test_result.php
![mama omr](https://cloud.githubusercontent.com/assets/431960/18905045/22969052-859c-11e6-8cfb-010ba904a1f4.png)

**Comment by inkukyang** [comment]
@zmania  처리완료
