### ISSUE TITLE
테스트 참여 > OMR 업로드 부분 체크

### ISSUE THREAD

**Issue by YUNDAN0131** [Mangongso/MamaOMR#70]
로컬 상태에서 OMR 업로드 선택 후 OMR 이미지 선택하면 아무런 응답없음.
로컬상태라서 그런 것인지, 라이브라면 작동되는 것인지 정확히 체크 할 것.
크롬/익스11 모두 해당

**Comment by zmania** [comment]
GD Library 가 php 5.4 이상에서 작동함 하위버전과 호환 가능하도록 수정 예정임

**Comment by zmania** [comment]
수정 완료 되었으며 http://mamaomr.hanbnc.com/ 에서 테스트 완료 되었음
