### ISSUE TITLE
크롬/익스11# 문제집 목록 > 테스트 참여에서 > OMR 다운로드 버튼 클릭 오류

### ISSUE THREAD

**Issue by YUNDAN0131** [Mangongso/MamaOMR#74]
문제집 목록 > 테스트 참여에서 > OMR 다운로드 버튼 클릭 하면 오류 뜸

크롬/익스11 모두 해당

**Comment by inkukyang** [comment]
다운로드가 윈도우 open으로 해당 이미지를 가져오게 되어있습니다. 
omr 이미지 없을수도 있을것 같은데요.. 확인을 원하시면 라이브에서 보거나 
원격으로 확인해 드릴게요

**Comment by zmania** [comment]
OMR 5시선다부터 2지 선다 까지 추가 되었음.
Book Class 의 getBoookTests 에서 guestion_type 추가 되었음.
