### ISSUE TITLE
마이 페이지 > 나의 매니징 > 리스트에 매니저 정보 없음

### ISSUE THREAD

**Issue by YUNDAN0131** [Mangongso/MamaOMR#77]
마이 페이지 > 나의 매니징 > 리스트에 매니저 정보 없음

**Comment by inkukyang** [comment]
나의 매니징 페이지 리스트는 자신이 매니징하고 잇는 학생드링 와야 합니다. 
현재 학생 이름과 학생이 푼문제의 목록이 리스트에 나오도록 하였습니다. 

라이브 반영 요청 하엿습니다.
