### ISSUE TITLE
마이페이지 텝

### ISSUE THREAD

**Issue by zmania** [Mangongso/MamaOMR#84]
마이페이지에 테스트 결과 보기로 들오가서 창 크기를 줄이면 텝이 아래로 떨어짐..

**Comment by YUNDAN0131** [comment]
메뉴 UL태그 끝에 "data-uk-tab"을 넣으면 해결됨
< ul class="uk-tab" data-uk-tab >

**Comment by YUNDAN0131** [comment]
수정완료
